name: Build site
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - uses: retypeapp/action-build@v1
      - name: Change /blob/ with /edit/
        run: |
          _retype_tmpdir="$(readlink -f "$(basename "$(find /tmp/tmp.* -type f \( -name "404.html" -o -name "index.html" \) | head -n1)")")";
          cd "$_retype_tmpdir";
          echo "$_retype_tmpdir";
          while read -r _file; do {
              sed -i 's|https://github.com/supremegamers/wiki/blob/main/|https://github.com/supremegamers/wiki/edit/main/|g' "$_file";
          } done < <(grep -lr 'https://github.com/supremegamers/wiki/blob/main/')
          
      - uses: retypeapp/action-github-pages@v1
        with:
          update-branch: true
